### ISSUE TITLE
[1.16.5] v1.1 does not work on servers

### ISSUE THREAD

**Issue by Discomanco** [Fuffled-Fuffles/TacticalFishing#1]
v1.1 crashes upon server startup.
Appears to be working fine on client bootup

MC 1.16.5
Forge 36.2.34
Tactical Fishing 1.1
JEI 7.7.1.152

```
-- Head --
Thread: main
Stacktrace:
	at com.fuffles.tactical_fishing.common.Registry.registerRecipeType(Registry.java:19) ~[tactical_fishing:1.1] {re:classloading}
-- MOD tactical_fishing --
Details:
	Mod File: TacticalFishing-1.16.5-v1.1.jar
	Failure message: Tactical Fishing (tactical_fishing) encountered an error during the load_registries event phase
		java.lang.NoSuchMethodError: net.minecraft.util.registry.Registry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
	Mod Version: 1.1
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: net.minecraft.util.registry.Registry.func_212607_c(Lnet/minecraft/util/ResourceLocation;)Z
Stacktrace:
	at com.fuffles.tactical_fishing.common.Registry.registerRecipeType(Registry.java:19) ~[tactical_fishing:1.1] {re:classloading}
	at com.fuffles.tactical_fishing.common.Registry.onRecipeSerializerRegistry(Registry.java:29) ~[tactical_fishing:1.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_0_Registry_onRecipeSerializerRegistry_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:249) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:236) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:202) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.2.34.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.2.34.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.2.34.jar:?] {}

```
[crash-2022-04-25_15.11.38-fml.txt](https://github.com/Fuffled-Fuffles/TacticalFishing/files/8554826/crash-2022-04-25_15.11.38-fml.txt)

**Comment by WFPhantom** [comment]
Same with 1.18.2

**Comment by Fuffled-Fuffles** [comment]
Yep my bad, the mentioned method is a Client Side only method, fix deploying soon
